# Generated by Django 5.1.4 on 2025-05-20 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # account 엔티티 입력 제거 - account는 이제 Django 모델이 아니라 Spring에서 관리함
        # ("account", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_key", models.CharField(max_length=255)),
                ("order_id", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("provider", models.CharField(max_length=100)),
                ("method", models.CharField(max_length=100)),
                ("paid_at", models.DateTimeField()),
                ("receipt_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                # account는 이제 Spring에서 관리하기 때문에 ForeignKey 대신 IntegerField 사용
                ("account_id", models.IntegerField()),
                (
                    "orders_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.orders",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
            },
        ),
    ]
