# Generated by Django 5.1.4 on 2025-05-20 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("account_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="loginType",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="account_profile.accountlogintype",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="roleType",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="account.accountroletype",
            ),
        ),
    ]
