# Generated by Django 5.1.4 on 2025-05-20 08:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # account 엔티티 입력 제거 - account는 이제 Django 모델이 아니라 Spring에서 관리함
        # ("account", "0001_initial"),
        ("company_report", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marketing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("click_count", models.PositiveSmallIntegerField(default=1)),
                ("purchase", models.BooleanField(default=False)),
                (
                    "last_click_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                # account는 이제 Spring에서 관리하기 때문에 ForeignKey 대신 IntegerField 사용
                ("account_id", models.IntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketing",
                        to="company_report.companyreport",
                    ),
                ),
            ],
            options={
                "db_table": "marketing",
            },
        ),
    ]
