# Generated by Django 5.1.4 on 2025-05-20 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # account 엔티티 입력 제거 - account는 이제 Django 모델이 아니라 Spring에서 관리함
        # ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                # writer(account)는 이제 Spring에서 관리하기 때문에 ForeignKey 대신 IntegerField 사용
                ("writer_id", models.IntegerField()),
            ],
            options={
                "db_table": "review",
            },
        ),
    ]
