# Generated by Django 5.1.4 on 2025-05-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=50)),
                ("company_name", models.CharField(max_length=100)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("overview", models.TextField(blank=True, null=True)),
                ("welfare", models.TextField(blank=True, null=True)),
                ("salary_info", models.TextField(blank=True, null=True)),
                ("culture", models.TextField(blank=True, null=True)),
                ("review_summary", models.TextField(blank=True, null=True)),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
