# Generated by Django 5.1.4 on 2025-05-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InterviewData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "companyName",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("question", models.TextField()),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "interview_question_data_per_job_category",
            },
        ),
    ]
