from django.db.models import IntegerChoices

class TechStack(IntegerChoices):
    FULLSTACK = 1, "풀스택"
    BACKEND = 2, "백엔드/서버개발"
    FRONTEND = 3, "프론트엔드"
    WEB = 4, "웹개발"
    FLUTTER = 5, "Flutter"
    JAVA = 6, "Java"
    JAVASCRIPT = 7, "JavaScript"
    PYTHON = 8, "Python"
    VUE = 9, "Vue.js"
    API = 10, "API"
    MYSQL = 11, "MYSQL"
    MARIADB = 12, "MariaDB"
    REACT = 13, "ReactJS"
    ASP = 14, "ASP"
    ANGULAR = 15, "Angular"
    BOOTSTRAP = 16, "Bootstrap"
    NODE = 17, "Node.js"
    JQUERY = 18, "jQuery"
    PHP = 19, "PHP"
    JSP = 20, "JSP"
    GRAPHQL = 21, "GraphQL"
    HTML5 = 22, "HTML5"