# Generated by Django 5.1.4 on 2025-05-20 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # account 엔티티 입력 제거 - account는 이제 Django 모델이 아니라 Spring에서 관리함
        # ("account", "0001_initial"),
        ("membership_plan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "결제 대기"),
                            ("COMPLETED", "구독 완료"),
                            ("SHIPPING", "구독 중"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                # account는 이제 Spring에서 관리하기 때문에 ForeignKey 대신 IntegerField 사용
                ("account_id", models.IntegerField()),
            ],
            options={
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="OrderItems",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "membership_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="membership_plan.membership",
                    ),
                ),
                (
                    "orders",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="orders.orders",
                    ),
                ),
            ],
            options={
                "db_table": "orders_items",
            },
        ),
    ]
