# Generated by Django 5.1.4 on 2025-05-20 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # account 엔티티 입력 제거 - account는 이제 Django 모델이 아니라 Spring에서 관리함
        # ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duration_days", models.PositiveIntegerField()),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("DAY", "1일권"),
                            ("WEEK", "1주일권"),
                            ("MONTH", "1개월권"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "membership",
            },
        ),
        migrations.CreateModel(
            name="UserMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_renew_scheduled", models.BooleanField(default=False)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="membership_plan.membership",
                    ),
                ),
                # user(account)는 이제 Spring에서 관리하기 때문에 ForeignKey 대신 IntegerField 사용
                ("user_id", models.IntegerField()),
            ],
            options={
                "db_table": "user_membership",
            },
        ),
    ]
